### ISSUE TITLE
passwall 4-32-20210805后面版本不能订阅v2ray节点，esxi环境兼容问题吗？

### ISSUE THREAD

**Issue by tianiue** [Openwrt-Passwall/openwrt-passwall#1422]
esxi，ikuai+lean源码打包openwrt，不知道什么原因订阅不成功v2ray节点，ss正常，用vm环境安装又可以，4-32版使用正常，后面版本不行，是兼容性问题，还是什么？知道的解答一下，谢谢！

**Comment by VwEl** [comment]
我订阅规则和更新组件啥的都错误_(:з)∠)_

**Comment by jh0072110** [comment]
遇到问题优先选择重置一下psw好么？这issue很没营养啊……

**Comment by tianiue** [comment]
> 遇到问题优先选择重置一下psw好么？这issue很没营养啊……

重新打包，全新安装都是同样问题，要是重置有用就不来问了

**Comment by tmdDream** [comment]
同不能订阅

**Comment by handsomeji** [comment]
能否提供订阅链接？

**Comment by tmdDream** [comment]
可以的,能否私聊发送




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaorouji/openwrt-passwall"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月29日(星期三) 晚上6:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaorouji/openwrt-passwall] passwall 4-32-20210805后面版本不能订阅v2ray节点，esxi环境兼容问题吗？ (#1422)





 
能否提供订阅链接？
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiaorouji** [comment]
xiaoroujixxoo@gmail.com
